apps/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<item_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<item_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

apps/coupons/urls.py
from django.conf.urls import url
from .import views


urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

apps/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^sent/$', views.order_sent, name='order-sent'),
]

apps/product/urls.py
from django.conf.urls import url
from apps.product.views import *


urlpatterns = [
    # пока тут
    url(r'^delivery/$', Delivery.as_view(), name="delivery"),
    url(r'^payments/$', PaymentMethods.as_view(), name="payments"),
    url(r'^contacts/$', Contacts.as_view(), name="contacts"),

    url(r'^sales/$', Sales.as_view(), name="sales"),
    url(r'^actions/$', Actions.as_view(), name="actions"),
    url(r'^presents/$', Presents.as_view(), name="presents"),
    url(r'^hot/$', HotProposition.as_view(), name="hot"),
    url(r'^bonuses/$', Bonuses.as_view(), name="bonuses"),
    url(r'^product/(?P<slug>[\w-]+)/$', ItemDetail.as_view(), name="details"),
    url(r'^(?P<slug>[\w-]+)/$', GeneralCategory.as_view(), name="category"),
    url(r'^$', MainPage.as_view(), name="main_page"),
]

store_roma/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from store_roma import telegramm
from store_roma import search

admin.autodiscover()


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^search/$', search.GlobalSearch.as_view(), name="site-search"),
    url(r'^feedback/$', telegramm.handle, name='feedback'),
    url(r'^account/', include('apps.account.urls', namespace="account")),
    url(r'^cart/', include('apps.cart.urls', namespace="cart")),
    url(r'^orders/', include('apps.orders.urls', namespace="orders")),
    # url(r'^comment/', include('apps.comments.urls', namespace="comment")),
    url(r'^wall/', include('apps.wall.urls', namespace='wall')),
    url(r'^moderator/', include('apps.administrator.urls', namespace="moderator")),
    url(r'^auth/', include('apps.loginsys.urls', namespace="auth")),
    url(r'^coupons/', include('apps.coupons.urls', namespace="coupons")),
    url(r'^api/products/', include('apps.product.api.urls', namespace='product-api')),
    # url(r'^api/comments/', include('apps.comments.api.urls', namespace='comment-api')),
    url(r'^api/users/', include('apps.loginsys.api.urls', namespace='users-api')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('apps.payment.urls', namespace='payment')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('apps.product.urls', namespace="product")),
    prefix_default_language=False,
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=0, required=False)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

apps/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST
from apps.cart.cart import Cart
from apps.cart.forms import CartAddProductForm
from apps.product.models import Item
from apps.coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, item_id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=item_id)
    form = CartAddProductForm(request.POST)
    x = request.POST.get('quantity')
    if x == None: x = 1
    y = item.quantity
    if form.is_valid() and y >= int(x) :
        cart.add(item=item, quantity=form.cleaned_data['quantity'], update_quantity=form.cleaned_data['update'])
    return redirect(reverse('product:details', kwargs={'slug':item.slug}))


def cart_remove(request, item_id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=item_id)
    cart.remove(item)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/cart-detail.html', {'cart': cart,
                                                     'coupon_apply_form': coupon_apply_form })

templates/cart/cart-detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Cart detail' %}
{% endblock title %}

{% block slider %}
{% endblock slider %}

{% block main-content %}
    <div class="row" id="cart">
        <div class="col-lg-12">
            <h3>{% trans 'Your cart' %}</h3>
            {% if cart %}
            <table class="cart">
                <thead>
                    <tr>
                        <th>{% trans 'Image' %}</th>
                        <th>{% trans 'Product' %}</th>
                        <th>{% trans 'Quantity' %}</th>
                        <th>{% trans 'Remove' %}</th>
                        <th>{% trans 'Unit price' %}</th>
                        <th>{% trans 'Total price' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                        {% with product=item.item %}
                            <tr>
                                <td>
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="{% if product.image %}{{ product.image.url }}{% endif %}" class="img-responsive">
                                    </a>
                                </td>
                                <td>
                                    <h2>{{product.item_title}}</h2>
                                </td>
                                <td>
                                    <form action="{% url "cart:cart_add" product.id %}" method="post" class="update-cart-form">
                                        <input type="number" name="quantity" min="0" max="{{ product.quantity }}" id="id_quantity" value="{{ item.quantity }}">
                                        {{ item.update_quantity_form.update }}
                                        {% csrf_token %}
                                        <input type="submit" value="{% trans 'Change' %}">

                                    </form>
                                </td>
                                <td>
                                    <a href="{% url "cart:cart_remove" product.id %}" class="remove-from-cart">{% trans 'Remove' %}</a>
                                </td>
                                <td>
                                    <p class="cart-detail-unit">{{ item.price|floatformat:"2" }}</p>
                                </td>
                                <td>
                                    <p class="cart-detail-total">{{ item.total_price|floatformat:"2" }}</p>
                                </td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                </tbody>
                <tfoot>
                    {% if cart.coupon %}
                    <tr class="subtotal">
                        <td>{% trans 'Subtotal' %}</td>
                        <td colspan="4"></td>
                        <td>{{cart.get_total_price|floatformat:"2"}}</td>
                    </tr>
                    <tr>
                        {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                        <td>"{{ code }}" coupon ({{ discount }})% off</td>
                        {% endblocktrans %}
                        <td colspan="4"></td>
                        <td class="num neg">- ${{cart.get_discount|floatformat:"2"}}</td>
                    </tr>
                    {% endif %}
                    <tr class="total">
                        <td>{% trans 'Total' %}</td>
                        <td colspan="4"></td>
                        <td class="num">${{cart.get_total_price_after_discount|floatformat:"2"}}</td>
                    </tr>
                </tfoot>
            </table>

            <p class="cart-coupon-p">{% trans 'Apply a coupon' %}:</p>

            <form action="{% url 'coupons:apply' %}" method="post" class="coupon-form">
                {{ coupon_apply_form }}
                {% csrf_token %}
                <input type="submit" value="{% trans 'Apply' %}">
            </form>

            <p class="text-right">
                <a href="{% url 'product:main_page' %}" class="btn btn-default">{% trans 'Continue shopping' %}</a>
                <a href="{% url 'orders:order_create' %}" class="btn btn-danger">{% trans 'Checkout' %}</a>
            </p>
        {% else %}
            <h4>{% trans 'Your cart is clear' %}</h4>
            <p><a href="{% url 'product:main_page' %}" class="return-to-shopping">{% trans 'Return to shopping' %}</a></p>
        {% endif %}
        </div>
    </div>
{% endblock main-content %}