apps/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<item_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<item_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

apps/product/api/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^categories/$', CategoriesListAPIView.as_view(), name='category-list'),
    url(r'^categories/(?P<pk>\d+)/$', CategoryDetailAPIView.as_view(), name='category-detail'),

    url(r'^$', ProductListAPIView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailAPIView.as_view(), name='detail'),
]

apps/product/urls.py
from django.conf.urls import url
from apps.product.views import *


urlpatterns = [
    # пока тут
    url(r'^delivery/$', Delivery.as_view(), name="delivery"),
    url(r'^payments/$', PaymentMethods.as_view(), name="payments"),
    url(r'^contacts/$', Contacts.as_view(), name="contacts"),

    url(r'^sales/$', Sales.as_view(), name="sales"),
    url(r'^actions/$', Actions.as_view(), name="actions"),
    url(r'^presents/$', Presents.as_view(), name="presents"),
    url(r'^hot/$', HotProposition.as_view(), name="hot"),
    url(r'^bonuses/$', Bonuses.as_view(), name="bonuses"),
    url(r'^product/(?P<slug>[\w-]+)/$', ItemDetail.as_view(), name="details"),
    url(r'^(?P<slug>[\w-]+)/$', GeneralCategory.as_view(), name="category"),
    url(r'^$', MainPage.as_view(), name="main_page"),
]

apps/wall/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^comment/(?P<id>\d+)/(?P<pk>\d+)/$', AddComment.as_view(), name='add-comment'),
    url(r'^comment/edit/(?P<id>\d+)/$', EditComment.as_view(), name='edit-comment'),
]

store_roma/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from store_roma import telegramm
from store_roma import search

admin.autodiscover()


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^search/$', search.GlobalSearch.as_view(), name="site-search"),
    url(r'^feedback/$', telegramm.handle, name='feedback'),
    url(r'^account/', include('apps.account.urls', namespace="account")),
    url(r'^cart/', include('apps.cart.urls', namespace="cart")),
    url(r'^orders/', include('apps.orders.urls', namespace="orders")),
    # url(r'^comment/', include('apps.comments.urls', namespace="comment")),
    url(r'^wall/', include('apps.wall.urls', namespace='wall')),
    url(r'^moderator/', include('apps.administrator.urls', namespace="moderator")),
    url(r'^auth/', include('apps.loginsys.urls', namespace="auth")),
    url(r'^coupons/', include('apps.coupons.urls', namespace="coupons")),
    url(r'^api/products/', include('apps.product.api.urls', namespace='product-api')),
    # url(r'^api/comments/', include('apps.comments.api.urls', namespace='comment-api')),
    url(r'^api/users/', include('apps.loginsys.api.urls', namespace='users-api')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('apps.payment.urls', namespace='payment')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('apps.product.urls', namespace="product")),
    prefix_default_language=False,
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/product/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.coupons.models import Coupon


class Category(models.Model):
    title = models.CharField(max_length=50, unique=True, default=None, verbose_name=_('Title'))
    title_ru = models.CharField(max_length=50, unique=True, blank=True, null=True, default=None)
    slug = models.SlugField(unique=True, default=None)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children', verbose_name=_('Parent'))
    created = models.DateField(auto_now_add=True, blank=True, null=True)
    cat_image = models.ImageField(upload_to="catbg", null=True, verbose_name=_('Cat_bg'))

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("product:category", kwargs={"slug": self.slug})

    def get_api_url(self):
        return reverse("product-api:category-detail", kwargs={"pk": self.pk})

    def items_in_category_count(self):
        return Item.objects.filter(category__slug=self.slug).count()

    def first_item_in_cat(self):
        return Item.objects.filter(category__slug=self.slug).first()


def create_category_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Category.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_category_slug(instance, new_slug=new_slug)
    return slug

def pre_save_category_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_category_slug(instance)

pre_save.connect(pre_save_category_post_receiver, sender=Category)


class Item(models.Model):
    item_title = models.CharField(max_length=100, unique=True, default=None, verbose_name=_('Item title'))
    item_title_ru = models.CharField(max_length=100, unique=True, blank=True, null=True, verbose_name=_('Item title'))
    slug = models.SlugField(unique=True, default=None)
    description = models.TextField(blank=True, null=True, default=None, verbose_name=_('Description'))
    # description_ru = models.TextField(blank=True, null=True, default=None, verbose_name=_('Description_ru'))
    quantity = models.PositiveIntegerField(verbose_name=_('Quantity')) #need replace quantity at stock
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_('Price'))
    image = models.ImageField(upload_to="item_images", null=True, verbose_name=_('Image'))
    category = models.ManyToManyField(Category, related_name='items', verbose_name=_('Category'))
    views = models.IntegerField(default=0, verbose_name=_('Views'))
    available = models.BooleanField(default=False, verbose_name=_('Avaliable'))
    discount = models.PositiveIntegerField( null=True, blank=True, default=0, verbose_name=_('Discount'))
    created_date = models.DateTimeField(default=timezone.now, verbose_name=_('Added'))
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name=_('Changed'))

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.item_title

    def update_counter(self, user):
        #  If user is anonymous, don't update counter, becouse can't add item to user viewed items
        if user.is_authenticated:
            viewed_item, created = ViewedItem.objects.get_or_create(user=user, product=self)
            viewed_item.update_counter()

    def get_price_with_discount(self):
        return self.price - self.price*(Decimal(self.discount)/100)

    def get_absolute_url(self):
        return reverse("product:details", kwargs={"slug": self.slug})

    def get_api_url(self):
        return reverse("product-api:detail", kwargs={"slug": self.slug})


def create_item_slug(instance, new_slug=None):
    slug = slugify(instance.item_title)
    if new_slug is not None:
        slug = new_slug
    qs = Item.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_item_slug(instance, new_slug=new_slug)
    return slug

def pre_save_item_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_item_slug(instance)

pre_save.connect(pre_save_item_post_receiver, sender=Item)


class ViewedItem(models.Model):
    user = models.ForeignKey(User, verbose_name=_('user'))
    product = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name=_('product'))
    date = models.DateField(auto_now=True)
    counter = models.IntegerField(default=1)

    def __str__(self):
        return self.product.item_title

    def update_counter(self):
        self.counter += 1
        self.save()
        return self

    class Meta:
        verbose_name = _('ViewedItem')
        verbose_name_plural = _('ViewedItems')

apps/product/forms.py
from django import forms


class ContactForm(forms.Form):
    phone = forms.CharField(max_length=20, required=True)

apps/product/api/views.py
from django.db.models import Q
from rest_framework import generics
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
from rest_framework.permissions import IsAdminUser, AllowAny
from rest_framework.filters import SearchFilter, OrderingFilter

from apps.product.api.permissions import IsAdminOrReadOnly
from .pagination import *
from .serializers import *


class CategoriesListAPIView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoriesListSerializer
    permission_classes = [AllowAny]
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title']

    def get_queryset(self, *args, **kwargs):
        queryset_list = super().get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(title__icontains=query)
        return queryset_list


class CategoryDetailAPIView(DestroyModelMixin, UpdateModelMixin, generics.RetrieveAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoryDetailSerializer
    permission_classes = [IsAdminUser]

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class ProductListAPIView(generics.ListAPIView):
    queryset = Item.objects.all()
    serializer_class = ProductListSerializer
    pagination_class = ProductLimitOffsetPagination
    permission_classes = [AllowAny]
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['item_title', 'description', 'user_first_name']

    def get_queryset(self, *args, **kwargs):
        queryset_list = super().get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(Q(item_title__icontains=query) |
                                                 Q(description__icontains=query) |
                                                 Q(user_first_name__icontains=query)).distinct()
        return queryset_list


class ProductDetailAPIView(DestroyModelMixin, UpdateModelMixin, generics.RetrieveAPIView):
    queryset = Item.objects.all()
    serializer_class = ProductDetailSerializer
    permission_classes = [IsAdminOrReadOnly]
    lookup_field = 'slug'

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

apps/product/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView
from django_filters.views import FilterView
from django.utils.translation import gettext as _

from apps.wall.forms import AddCommentForm
# from apps.wall.models import Message
from apps.wall.models import Comment
from split_testing.utils import ab_init

from apps.administrator.forms import ProductForm
from apps.cart.forms import CartAddProductForm
# from apps.comments.forms import CommentAddForm
# from apps.comments.models import Comment
from apps.product.filters import ProductFilter
from apps.product.forms import ContactForm
from .models import *


class MyMixin:
    def get_queryset(self, my_list=None):
        if not my_list:
            my_list = Item.objects.filter(category__slug=self.kwargs['slug']).order_by('item_title')
        return my_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feedback'] = ContactForm()
        return context


class MainPage(ListView):
    model = Item
    queryset = Item.objects.all()
    template_name = 'main.html'
    # alternative template for a-b split-testing
    alternative_template_name = 'alter-main.html'
    page_name = 'main page'

    def dispatch(self, request, *args, **kwargs):
        # init for a/b, add +1 to "Entered"
        ab_init(self)
        # call the view
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_items = self.queryset  # get all products in one request
        #  rendering viewed and recommended for user
        if self.request.user.is_authenticated:
            rec_list = []
            viewed_list = ViewedItem.objects.filter(user=self.request.user).order_by('counter')[:4]
            for item in viewed_list:
                main_cat = item.product.category.all().filter(parent=None)
                new_items = all_items.filter(Q(category=main_cat) & ~Q(item_title=item.product.item_title)).order_by('?')[1]
                rec_list.append(new_items)
            context['viewed'] = viewed_list
        else:
            # top views items for anonymous
            rec_list = all_items.order_by('views')[:4]
        # rows of products by characteristics
        context['category'] = Category.objects.filter(parent=None)
        context['promotions'] = all_items.filter(discount__gt=0).order_by('discount')[:4]
        context['novelties'] = all_items.order_by('created_date')[:4]
        context['recommended'] = rec_list
        context['feedback'] = ContactForm()
        return context


class Actions(TemplateView):
    template_name = 'actions.html'


class Presents(TemplateView):
    template_name = 'presents.html'


class HotProposition(TemplateView):
    template_name = 'hot-proposition.html'


class Bonuses(TemplateView):
    template_name = 'bonuses.html'


class Delivery(TemplateView):
    template_name = 'delivery.html'


class PaymentMethods(TemplateView):
    template_name = 'payment-methods.html'


class Contacts(TemplateView):
    template_name = 'contacts.html'


class Sales(FilterView, ListView):
    model = Item
    filterset_class = ProductFilter
    template_name = 'product/product-list.html'
    context_object_name = 'items'
    queryset = Item.objects.filter(discount__gt=0).order_by('discount')
    paginate_by = 1
    page_kwarg = _('page')


class GeneralCategory(FilterView, MyMixin, ListView):
    model = Item
    filterset_class = ProductFilter
    template_name = 'product/product-list.html'
    context_object_name = 'items'
    paginate_by = 1
    page_kwarg = _('page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        context['subcategories'] = Category.objects.filter(parent__slug=self.kwargs['slug'])
        return context


class ItemDetail(MyMixin, DetailView):
    """
    Item page
    """
    model = Item
    template_name = 'product/product-details.html'
    context_object_name = 'product'

    def get_object(self, queryset=None):
        queryset = Item.objects.get(slug=self.kwargs.get('slug'))
        queryset.update_counter(self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item_slug = self.kwargs['slug']

        if not 'visited_list' in self.request.session:
            self.request.session['visited_list'] = []

        if not item_slug in self.request.session['visited_list']:
            self.object.views += 1
            self.object.save()
            self.request.session['visited_list'].append(item_slug)

        context['addProdform'] = ProductForm  # remove in future
        context['cart_product_form'] = CartAddProductForm()
        context['comments'] = Comment.objects.filter(product__slug=self.kwargs['slug'])
        context['popular_item_list'] = Item.objects.order_by('-views')[:4]
        context['sales_item_list'] = Item.objects.filter(discount__gt=0)[:4]
        context['AddCommentForm'] = AddCommentForm()
        return context

templates/product/paginator.html
{% load static %}
{% load paginator_repair %}
{% load i18n %}

<div class="col-lg-12 paginator">
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
            <span><a href="?{% url_replace page=page_obj.previous_page_number %}">{% trans 'Prev' %}</a></span>
        </li>
        {% endif %}
        <li class="">
            {% for page in page_obj.paginator.page_range %}
                {% ifequal page page_obj.number %}
                    <a class="active-page">
                        {{page}}
                    </a>
                {% else %}
                    <a href="?{% url_replace page=page %}">
                        {{page}}
                    </a>
                {% endifequal %}
            {% endfor %}
        </li>
        {% if page_obj.has_next %}
        <li>
            <span><a href="?{% url_replace page=page_obj.next_page_number %}">{% trans 'Next' %}</a></span>
        </li>
        {% endif %}
    </ul>
    {% endif %}
</div>

templates/product/product-details.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}
{% load comment_filter %}


{% block title %}
    {% trans 'Product page' %}
{% endblock title %}

{% block slider %}
{% endblock slider %}

{% block main-content %}
    <section class="row product-detail-wrapper">
        <div class="col-lg-12">
            <h1>{{product|translate_field:'item_title'}}</h1>
        </div> <!-- h1 -->
        <div class="col-lg-6 col-md-4 col-sm-4 col-xs-4 thumbnail">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="img-responsive item-preview"/>
            {% endif %}
        </div> <!-- product image block -->
        <div class="col-lg-6 col-md-8 col-sm-8 col-xs-8 product-all-info">
            <div class="prod-detail-price">
                <!-- If product have discount linked 2 price else 1 -->
                {% if product.discount > 0 %}
                    <span class="item-price old-price">${{product.price}}</span>
                    <span class="item-price discount-price">
                        ${{ product.get_price_with_discount|floatformat:"2" }}
                    </span>
                {% else %}
                    <p class="item-price discount-price">${{product.price}}</p>
                {% endif %}
            </div> <!-- product price block -->
            <div class="buyed">
                {% if product.id|slugify in cart.cart.keys %}
                    <!-- If product added in cart buy-button switched for link to move cart-detail -->
                    <a href="{% url "cart:cart_detail" %}">
                        <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
                        <span>{% trans 'Product in cart' %}</span>
                    </a>
                {% else %}
                    {% if product.quantity != 0 %}
                        <form action="{% url "cart:cart_add" product.id %}"
                              method="post" id="add-product-in-cart" class="add-cart-form">
                            <input type="hidden" name="quantity" id="id_quantity" value="1" disabled="disabled">
                            {% csrf_token %}
                            <input type="submit" value="{% trans 'Add to cart' %}" id="confirm-add-product">
                        </form>
                    {% else %}
                        <span class="not-available">{% trans 'The goods are not yet available' %}</span>
                    {% endif %}
                {% endif %}
            </div> <!-- add to cart form -->
            <div class="wishlist">
                <!-- Two empty forms for add to wishlist, watch-the-price is wishlist too -->
                <form action="" method="post" class="form-wishlist">
                    <!-- Empty form -->
{#                            <input type="hidden" name="quantity" id="id_quantity" value="1" disabled="disabled">#}
                    {% csrf_token %}
                    <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
                    <input type="submit" value="{% trans 'Add to wishlist' %}">
                </form>
                <form action="" method="post" class="form-watch-the-price">
                    <!-- Empty form -->
{#                            <input type="hidden" name="quantity" id="id_quantity" value="1" disabled="disabled">#}
                    {% csrf_token %}
                    <i class="glyphicon glyphicon-flag" aria-hidden="true"></i>
                    <input type="submit" value="{% trans 'Watch the price' %}">
                </form>
            </div> <!-- wish list block -->
            <!-- Discount countdown -->
            {% if product.discount > 0 and product.quantity > 0 %}
                <div class="discount-counter">
                    <p>{% trans 'Actions! Sales! Until the end of the campaign is left' %}:</p>
                    <img src="{% static 'media/work_images/discount.png' %}" alt="">
                    <div class="defaultCountdown"></div>
                </div>
            {% endif %}
            <div id="info">
                {% if product.quantity == 0 %}
                    <p>{% trans 'The goods ended. Add it to your wishlist and we will notify you when it appears' %}</p>
                {% endif %}
                <p class="info-2">
                    <i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i>
                    {% trans 'Seen' %}
                    <span>{{product.views}}</span>
                    {% trans 'times' %}
                </p>
                <p class="info-3">
                    <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
                    <span>0</span>
                    {% trans 'People added to wishlist' %}
                </p>
                <p class="info-in-action">
                    {% if product.in_action %}  <!-- In this time product don't have this method -->
                        {% trans 'This product participates in the promotion.' %}
                        <span>
                            {% trans 'About the details of the action you can find' %}
                            <a href="#">{% trans 'here' %}</a>
                        </span>
                    {% else %}
                        {% trans 'This product does not yet participate in promotions.' %}
                    {% endif %}
                </p>
                <ul class="product-in-categories">
                    <li>
                        <p>{% trans 'Product in categories' %}:</p>
                    </li>
                    {% for cat in product.category.all %}
                        <li>
                            <a href="{{ cat.get_absolute_url }}">
                                {{ cat|translate_field:'title'}}
                            </a>
                        </li>
                    {% endfor %}
                </ul> <!-- Categories product -->
            </div> <!-- All product info -->
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div id="description">
                <h2 class="h-in-tabs">{% trans 'Description' %}</h2>
                <p class="item-desc">{{ product.description|truncatechars_html:300 }}</p>
            </div> <!-- description -->
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="row">
                <div id="app">
                    <form action="" method="POST" style="display: none" class="comment_form">
                        {% csrf_token %}
                        <p class="comment_text">{{ AddCommentForm }}</p>
                        <input type="submit" class="submit-comment-button">
                    </form><!-- Форма для комментариев, не отображается -->
                    <div class="message-container infinite-container">
                        <div class="message-wrapper infinite-item">
                            <div class="message-body">
                                <!-- data-url используется ajax для создания комментария при клике на ссылку "комментировать" ниже -->
                                <span class='message-date' data-url="{% url 'wall:add-comment' id=product.id pk=0 %}"></span>
                                {% if request.user.is_authenticated %}
                                    <a class="comment">
                                        <i class="glyphicon glyphicon-pushpin" aria-hidden="true"></i>
                                        {% trans 'comment' %}
                                    </a>
                                {% endif %}
                                {% if product.comments.all %}
                                    <p class="show-content">{% trans 'Show all comments' %}</p>
                                {% else %}
                                    <p class="no-comments">{% trans 'No comments here' %}</p>
                                {% endif %}
                            </div><!-- Блок сообщения, без комментариев -->
                            <div class="all-comments">
                                {% if product.comments.all %}
                                    {% for comment in product.comments|parent_filter %}<!-- Фильтр для выборки комментариев верхнего уровня -->
                                        <div class="comment_div">
                                            <div class="comment-wrapper">
                                                {% if request.user == comment.author or request.user.is_staff %}
                                                    <a href="{% url 'wall:edit-comment' id=comment.id %}" class="edit-comment">
                                                        {% trans 'edit comment' %}
                                                    </a>
                                                {% endif %}
                                                <p data-comment_id="{{ comment.id }}" class="comment-text">{{ comment.body }}</p>
                                                {% if comment.posted == comment.edited %}
                                                    {% trans 'comment posted' %}
                                                {% else %}
                                                    {% trans 'comment edited' %}
                                                {% endif %}
                                                <span class='comment-author'>{{ comment.author }}</span>
                                                <!-- data-url используется ajax для создания комментария при клике на ссылку "комментировать" ниже -->
                                                <span class='comment-date' data-url="{% url 'wall:add-comment' id=product.id pk=comment.id %}">
                                                    {{ comment.posted }}
                                                </span>
                                                {% if request.user.is_authenticated %}
                                                    <a class="reply">{% trans 'reply' %}</a>
                                                {% endif %}
                                            </div><!-- Блок комментария -->
                                            <div class="all-comments">
                                                {% if comment.children.all %}
                                                    {% include 'wall/comment.html' with comments=comment.children.all %}
                                                {% endif %}
                                            </div><!-- Контейнер для дочерних комментариев -->
                                        </div><!-- Контейнер для каждого комментария, включая дочерние -->
                                    {% endfor %}
                                {% else %}
                                    <p class="void-class special">{% trans 'No comments here' %}</p>
                                {% endif %}
                            </div><!-- Контейнер для всех комментариев к сообщению -->
                        </div><!-- Контейнер сообщения, включая его комментарии -->
                    </div><!-- Контейнер для всех сообщений -->
                </div>
            </div>
        </div>
    </section>
{% endblock main-content %}

templates/product/product-list.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load models_trans %}


{% block main-content %}
    <section id="content-section" class="row">
        <!-- Temle off filter on sm dislays for refactoring -->
        <aside class="col-lg-3 col-md-3 hidden-sm">
            {% block filters %}
                {% include 'filters.html' %}
            {% endblock filters %}
        </aside> <!-- filters block -->
        <article id="categories" class="col-lg-9 col-md-9 col-xs-12 main-content">
            {% if subcategories %}
                <div class="sub-navigation">
                    <ul>
                        {% for category in subcategories %}
                            <li>
                                <a href="{% url 'product:category' category.slug %}">
                                    {{category|translate_field:"title"}}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div> <!-- sub-navigation if get page from category navigation -->
            {% endif %}
            {% if items %}
                {% for product in items %}
                    <div class="col-lg-3 col-md-3 col-xs-4 block">
                        {% include 'product/product.html' %}
                    </div>
                {% endfor %}
                {% block paginator %}
                    {% include 'product/paginator.html' %}
                {% endblock paginator %}
            {% else %}
                <h3>{% trans 'No categories here' %}</h3>
            {% endif %}
        </article>
    </section>
{% endblock main-content %}