apps/account/urls.py
from django.conf.urls import url
from apps.account.views import *


urlpatterns = [
    url(r'^(?P<id>\d+)$', ProfilePage.as_view(), name="page"),
    # url(r'^product/(?P<slug>[\w-]+)/$', ItemDetail.as_view(), name="details"),
    # url(r'^(?P<slug>[\w-]+)/$', GeneralCategory.as_view(), name="category"),
    # url(r'^$', MainPage.as_view(), name="main_page"),
]

apps/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<item_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<item_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

apps/loginsys/urls.py
from django.conf.urls import url
from apps.loginsys import views


urlpatterns = [
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^register/$', views.register, name="register"),
]

apps/product/urls.py
from django.conf.urls import url
from apps.product.views import *


urlpatterns = [
    # пока тут
    url(r'^delivery/$', Delivery.as_view(), name="delivery"),
    url(r'^payments/$', PaymentMethods.as_view(), name="payments"),
    url(r'^contacts/$', Contacts.as_view(), name="contacts"),

    url(r'^sales/$', Sales.as_view(), name="sales"),
    url(r'^actions/$', Actions.as_view(), name="actions"),
    url(r'^presents/$', Presents.as_view(), name="presents"),
    url(r'^hot/$', HotProposition.as_view(), name="hot"),
    url(r'^bonuses/$', Bonuses.as_view(), name="bonuses"),
    url(r'^product/(?P<slug>[\w-]+)/$', ItemDetail.as_view(), name="details"),
    url(r'^(?P<slug>[\w-]+)/$', GeneralCategory.as_view(), name="category"),
    url(r'^$', MainPage.as_view(), name="main_page"),
]

store_roma/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from store_roma import telegramm
from store_roma import search

admin.autodiscover()


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^search/$', search.GlobalSearch.as_view(), name="site-search"),
    url(r'^feedback/$', telegramm.handle, name='feedback'),
    url(r'^account/', include('apps.account.urls', namespace="account")),
    url(r'^cart/', include('apps.cart.urls', namespace="cart")),
    url(r'^orders/', include('apps.orders.urls', namespace="orders")),
    # url(r'^comment/', include('apps.comments.urls', namespace="comment")),
    url(r'^wall/', include('apps.wall.urls', namespace='wall')),
    url(r'^moderator/', include('apps.administrator.urls', namespace="moderator")),
    url(r'^auth/', include('apps.loginsys.urls', namespace="auth")),
    url(r'^coupons/', include('apps.coupons.urls', namespace="coupons")),
    url(r'^api/products/', include('apps.product.api.urls', namespace='product-api')),
    # url(r'^api/comments/', include('apps.comments.api.urls', namespace='comment-api')),
    url(r'^api/users/', include('apps.loginsys.api.urls', namespace='users-api')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('apps.payment.urls', namespace='payment')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('apps.product.urls', namespace="product")),
    prefix_default_language=False,
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/actions.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Actions page' %}</h1>
        <p>{% trans 'There will be a list of all the actions' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/alter-main.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="row"> <!-- all content -->
        <div class="left-content col-lg-9 col-md-9 col-sm-12"> <!-- left section for all content -->
            <section class="col-lg-4 col-md-4 col-sm-12 sidebar"> <!-- sidebar section -->
                <h3 class="goods">{% trans 'Product groups' %}</h3>
                <ul class="goods-list">
                    {% for cat in category %}
                        {% if cat.title and cat.title != 'brands' %}
                        <a href="{{ cat.get_absolute_url }}">
                            <li>
                                <p>{{cat|translate_field:'title'}}  ({{ cat.items_in_category_count }})</p>
                            </li>
                        </a>
                        {% endif %}
                    {% endfor %}
                </ul>
            </section> <!-- sidebar section -->

            <section class="col-lg-8 col-md-8 col-sm-12" id="slider"> <!-- mid content -->
                <div class="zavlekuha"> <!-- navigation with promotions -->
                    <ul title="{% trans 'all links except the last lead on informative pages at the moment' %}">
                        <li>
                            <i class="glyphicon glyphicon-bullhorn" aria-hidden="true"></i>
                            <a href="{% url 'product:actions' %}">{% trans 'actions' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-gift" aria-hidden="true"></i>
                            <a href="{% url 'product:presents' %}">{% trans 'presents' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-fire" aria-hidden="true"></i>
                            <a href="{% url 'product:hot' %}">{% trans 'hot proposition' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></i>
                            <a href="{% url 'product:bonuses' %}">{% trans 'bonuses' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-arrow-down" aria-hidden="true"></i>
                            <a href="{% url 'product:sales' %}">{% trans 'sales' %}</a>
                        </li>
                    </ul>
                </div>

                <div class="slider"> <!-- slider -->
                    <img src="{% static 'media/temple_for_slider/slider1.jpg' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider2.png' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider3.JPG' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider4.jpg' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider5.JPG' %}" class="img-responsive">
                </div>

                <div class="sign-up"> <!-- sign up button -->
                    <h3>{% trans 'Please register to participate in promotions, receive bonuses and discounts!' %}</h3>
                    <button><a href="{% url 'auth:register' %}">Registration</a></button>
                </div>
             </section> <!-- mid content -->

            <section class="col-lg-12" id="viewed-items"> <!-- viewed products -->
                <h3>{% trans 'Viewed items' %}</h3>
                {% if viewed %}
                    {% for item in viewed %}
                        {% with item.product as product %}
                            <article class="col-lg-3 col-md-4 col-xs-6 block">
                                {% include 'product/product.html' %} <!-- product presentation -->
                            </article>
                        {% endwith %}
                    {% endfor %}
                {% else %}
                    <!-- Task for Future special block for non-auth user -->
                    <p>Тут еще ведутся работы</p>
                {% endif %}
            </section> <!-- viewed products -->

            <section class="col-lg-12" id="recommended"> <!-- recommended items section -->
                <h3>{% trans 'Recommended' %}</h3>
                {% if recommended %}
                    {% for product in recommended %}
                        <article class="col-lg-3 col-md-4 col-xs-6 block">
                            {% include 'product/product.html' %} <!-- product presentation -->
                        </article>
                    {% endfor %}
                {% else %}
                    <p>balalayka</p>
                {% endif %}
            </section> <!-- recommended section -->

            <section class="col-lg-12" id="promotions"> <!-- promotions section -->
                <h3>{%trans 'Promotions'%}</h3>
                {% if promotions %}
                    {% for product in promotions %}
                        <article class="col-lg-3 col-md-4 col-xs-6 block">
                            {% include 'product/product.html' %} <!-- product presentation -->
                        </article>
                    {% endfor %}
                {% else %}
                    <p>No promotions in here</p>
                {% endif %}
            </section> <!-- promotions section -->

            <section class="col-lg-12" id="novelties"> <!-- novelties section -->
                <h3>{%trans 'Novelties'%}</h3>
                {% if novelties %}
                    {% for product in novelties %}
                        <article class="col-lg-3 col-md-4 col-xs-6 block">
                            {% include 'product/product.html' %} <!-- product presentation -->
                        </article>
                    {% endfor %}
                {% else %}
                    <p>No items</p>
                {% endif %}
            </section> <!-- novelties section -->
        </div> <!-- left section all content -->

        <div class="right-content col-lg-3 col-md-3 hidden-sm"> <!-- right content -->
            <section>
                <ul class="hot-promotion-list"> <!-- presentation top promotions list -->
                    {% for promotion in promotions %}
                        <a href="{{ promotion.get_absolute_url }}">
                            <li>
                                <img src="{{ promotion.image.url }}" class="img-responsive" alt="promotion-img">
                                <h3>
                                    {% trans 'Hot proposition' %} for
                                    <span class="promotion-item">{{ promotion.item_title }}</span>
                                </h3>
                                <p>
                                    {% trans 'Instead' %} {{ promotion.price }}
                                    {% trans 'new price' %}
                                    <span>
                                        {{ promotion.get_price_with_discount|floatformat:"2" }}
                                    </span>
                                </p>
                                <p class="promotion-discount">
                                    {% trans 'A discount' %} - <span>{{ promotion.discount }}% .</span>
                                    {% trans 'Hurry up' %}
                                    <a href="{{ promotion.get_absolute_url }}">{% trans 'details promotion' %}!</a>
                                </p>
                            </li>
                        </a>
                    {% endfor %}
                </ul> <!-- end promotions list -->
            </section>
        </div>
    </div>
{% endblock main-content %}

templates/bonuses.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Bonuses page' %}</h1>
        <p>{% trans 'Some.....' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Contacts' %}</h1>
        <p>{% trans 'Contacts. Not necessarily a separate page. Possible and pop-up window... Google maps.' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/delivery.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Delivery' %}</h1>
        <p>{% trans 'Ways of delivery. Not necessarily a separate page. Possible and pop-up window' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/hot-proposition.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Hot proposition page' %}</h1>
        <p>{% trans 'There will be a list of all hot propositions' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="row"> <!-- all content -->
        <div class="left-content col-lg-9 col-md-9 col-sm-12"> <!-- left section for all content -->
            <section class="col-lg-4 col-md-4 col-sm-12 sidebar"> <!-- sidebar section -->
                <h3 class="goods">{% trans 'Product groups' %}</h3>
                <ul class="goods-list">
                    {% for cat in category %}
                        {% if cat.title and cat.title != 'brands' %}
                        <a href="{{ cat.get_absolute_url }}">
                            <li>
                                <p>{{cat|translate_field:'title'}}  ({{ cat.items_in_category_count }})</p>
                            </li>
                        </a>
                        {% endif %}
                    {% endfor %}
                </ul>
            </section> <!-- sidebar section -->

            <section class="col-lg-8 col-md-8 col-sm-12" id="slider"> <!-- mid content -->
                <div class="zavlekuha"> <!-- navigation with promotions -->
                    <ul title="{% trans 'all links except the last lead on informative pages at the moment' %}">
                        <li>
                            <i class="glyphicon glyphicon-bullhorn" aria-hidden="true"></i>
                            <a href="{% url 'product:actions' %}">{% trans 'actions' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-gift" aria-hidden="true"></i>
                            <a href="{% url 'product:presents' %}">{% trans 'presents' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-fire" aria-hidden="true"></i>
                            <a href="{% url 'product:hot' %}">{% trans 'hot proposition' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></i>
                            <a href="{% url 'product:bonuses' %}">{% trans 'bonuses' %}</a>
                        </li>
                        <li>
                            <i class="glyphicon glyphicon-arrow-down" aria-hidden="true"></i>
                            <a href="{% url 'product:sales' %}">{% trans 'sales' %}</a>
                        </li>
                    </ul>
                </div>

                <div class="slider"> <!-- slider -->
                    <img src="{% static 'media/temple_for_slider/slider1.jpg' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider2.png' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider3.JPG' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider4.jpg' %}" class="img-responsive">
                    <img src="{% static 'media/temple_for_slider/slider5.JPG' %}" class="img-responsive">
                </div>

                <div class="sign-up"> <!-- sign up button -->
                    <h3>{% trans 'Please register to participate in promotions, receive bonuses and discounts!' %}</h3>
                    <button><a href="{% url 'auth:register' %}">Registration</a></button>
                </div>
             </section> <!-- mid content -->

            <section class="col-lg-12" id="viewed-items"> <!-- viewed products -->
                <h3>{% trans 'Viewed items' %}</h3>
                {% if viewed %}
                    {% for item in viewed %}
                        {% with item.product as product %}
                            <article class="col-lg-3 col-md-4 col-xs-6 block">
                                {% include 'product/product.html' %} <!-- product presentation -->
                            </article>
                        {% endwith %}
                    {% endfor %}
                {% else %}
                    <!-- Task for Future special block for non-auth user -->
                    <p>Тут еще ведутся работы</p>
                {% endif %}
            </section> <!-- viewed products -->

            <section class="col-lg-12" id="recommended"> <!-- recommended items section -->
                <h3>{% trans 'Recommended' %}</h3>
                {% if recommended %}
                    {% for product in recommended %}
                        <article class="col-lg-3 col-md-4 col-xs-6 block">
                            {% include 'product/product.html' %} <!-- product presentation -->
                        </article>
                    {% endfor %}
                {% else %}
                    <p>balalayka</p>
                {% endif %}
            </section> <!-- recommended section -->

            <section class="col-lg-12" id="promotions"> <!-- promotions section -->
                <h3>{%trans 'Promotions'%}</h3>
                {% if promotions %}
                    {% for product in promotions %}
                        <article class="col-lg-3 col-md-4 col-xs-6 block">
                            {% include 'product/product.html' %} <!-- product presentation -->
                        </article>
                    {% endfor %}
                {% else %}
                    <p>No promotions in here</p>
                {% endif %}
            </section> <!-- promotions section -->

            <section class="col-lg-12" id="novelties"> <!-- novelties section -->
                <h3>{%trans 'Novelties'%}</h3>
                {% if novelties %}
                    {% for product in novelties %}
                        <article class="col-lg-3 col-md-4 col-xs-6 block">
                            {% include 'product/product.html' %} <!-- product presentation -->
                        </article>
                    {% endfor %}
                {% else %}
                    <p>No items</p>
                {% endif %}
            </section> <!-- novelties section -->
        </div> <!-- left section all content -->

        <div class="right-content col-lg-3 col-md-3 hidden-sm"> <!-- right content -->
            <section>
                <ul class="hot-promotion-list"> <!-- presentation top promotions list -->
                    {% for promotion in promotions %}
                        <a href="{{ promotion.get_absolute_url }}">
                            <li>
                                <img src="{{ promotion.image.url }}" class="img-responsive" alt="promotion-img">
                                <h3>
                                    {% trans 'Hot proposition' %} for
                                    <span class="promotion-item">{{ promotion.item_title }}</span>
                                </h3>
                                <p>
                                    {% trans 'Instead' %} {{ promotion.price }}
                                    {% trans 'new price' %}
                                    <span>
                                        {{ promotion.get_price_with_discount|floatformat:"2" }}
                                    </span>
                                </p>
                                <p class="promotion-discount">
                                    {% trans 'A discount' %} - <span>{{ promotion.discount }}% .</span>
                                    {% trans 'Hurry up' %}
                                    <a href="{{ promotion.get_absolute_url }}">{% trans 'details promotion' %}!</a>
                                </p>
                            </li>
                        </a>
                    {% endfor %}
                </ul> <!-- end promotions list -->
            </section>
        </div>
    </div>
{% endblock main-content %}

templates/messages_display.html
{% if messages %}
    {% for message in messages %}
        {%  if "html_safe" in message.tags %}
            {{ message|safe }}
        {% else %}
            {{ message }}
        {% endif %}
    {% endfor %}
{% endif %}

templates/payment-methods.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Payment methods' %}</h1>
        <p>{% trans 'Payments......' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/presents.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load models_trans %}


{% block nav %}
{% endblock nav %}

{% block main-content %}
    <div class="stub">
        <h1>{% trans 'Presents page' %}</h1>
        <p>{% trans 'There will be a gift shop' %}</p>
        <a href="{% url 'product:main_page' %}">Home</a>
    </div>
{% endblock main-content %}

templates/top-section.html
{% load static %}

{% load i18n %}

<div class="container-fluid">
    <div class="row">

        {% if not request.user.is_anonymous %}
            <div class="col-lg-12 dashboard">
                {% if request.user.is_superuser %}
                    <a href="{% url 'moderator:panel' %}" class="administration-link">
                        {% trans 'Administration' %}
                    </a>
                    <a href="{% url 'account:page' user.id %}">{% trans 'Enter your dashboard' %}</a>
                {% else %}
                    <a href="{% url 'account:page' user.id %}">{% trans 'Enter your dashboard' %}</a>
                {% endif %}
            </div> <!-- dashboard -->
        {% endif %}

        <div class="col-lg-2">
            <div class="logo-wrapper">
                <i class="glyphicon glyphicon-knight" aria-hidden="true"></i>
            </div>
        </div> <!-- logotype -->

        <div class="col-lg-2 feedback">
            <p class="feedback-first-line">8(050)123-45-67</p>
            <p class="feedback-second-line">8(050)123-45-67</p>
            <p class="feedback-third-line">{% trans 'we will call you back!' %}</p>
            <form action="{% url 'feedback' %}" class="feedback-form" method="post" name="super">
                <input type="text" name="phone" maxlength="20" required="" id="id_phone" placeholder="You phone number">
                {% csrf_token %}
                <a href="javascript:document.super.submit()">
                    <i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>
                </a>
            </form>
        </div> <!-- feedback form block -->

        <div class="col-lg-8">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-10 col-md-10">
                        <nav class="base-navigation">
                            <li><a href="{% url 'product:actions' %}">{% trans 'Actions' %}</a></li>
                            <li><a href="{% url 'product:payments' %}">{% trans 'Payment' %}</a></li>
                            <li><a href="{% url 'product:delivery' %}">{% trans 'Delivery' %}</a></li>
                            <li><a href="{% url 'product:contacts' %}">{% trans 'Contacts' %}</a></li>
                        </nav>
                    </div> <!-- site navigation -->

                    <div class="col-lg-2 col-md-2">
                        <form action="{% url 'set_language' %}" method="post" class="languages-form">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}" />
                            <ul>
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}

                            {% for language in languages %}
                                <li>
                                    <button type="submit"
                                            name="language"
                                            value="{{ language.code }}"
                                            class="{% if language.code == LANGUAGE_CODE %}selected-lang{% endif %}">
                                        {{ language.code }}
                                    </button>
                                </li>
                            {% endfor %}
                            </ul>
                        </form>
                    </div> <!-- Choose language block -->
                </div>

                <div class="row">
                    <div class="col-lg-8">
                        <div class="global-search">
                            <form action="{% url 'site-search' %}" method="get" accept-charset="utf-8" name="global_search">
                                <div class="input-group">
                                {% csrf_token %}
                                <input class="searchfield" id="searchbox" name="bigs"
                                       type="text" placeholder="{% trans 'Search' %}" class="form-control">
                                <span class="input-group-btn">
                                <a href="javascript:document.global_search.submit()" class="btn btn-default">
                                    <i class="glyphicon glyphicon-search" aria-hidden="true"></i>
                                </a>
                                </span>
                                </div>
                            </form>
                        </div>
                    </div> <!-- global search block -->

                    <div class="col-lg-1 in-out">
                        {% if not request.user.is_authenticated %}
                            <a href="" data-toggle="modal" data-target="#login-popup">
                                <i class="glyphicon glyphicon-user" aria-hidden="true"></i>
                                <p>
                                    {% trans 'login' %}
                                </p>
                            </a>
                            <!-- Modal -->
                            <div class="modal fade" id="login-popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">LOGIN FORM</h4>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{% url 'auth:login' %}" method="post" class="login-form">
                                                {% csrf_token %}
                                                <input type="text" name="username" id="username" placeholder="{% trans 'Your name here' %}...">
                                                <input type="password" name="password" id="password" placeholder="{% trans 'Your password' %}...">
                                                <button>{% trans 'Login' %}</button>
                                                <a href="{% url 'auth:register' %}">{% trans 'Registration' %}</a>
                                                {% if login_error %}
                                                    <label>{{login_error}}</label>
                                                {% endif %}
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <a href="{% url 'auth:logout' %}">
                                <i class="glyphicon glyphicon-user" aria-hidden="true"></i>
                                <p>
                                    {% trans 'logout' %}
                                </p>
                            </a>
                        {% endif %}
                    </div> <!-- login/logout block -->
                    <div class="col-lg-3">
                        <ul class="shopify">
                            <li>
                                <i class="glyphicon glyphicon-stats" aria-hidden="true"></i>
                                <p>{% trans 'compare' %}</p>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
                                    <span class="badge">0</span>
                                    <p>{% trans 'desires' %}</p>
                                </a>
                            </li> <!-- Empty block wish list count -->
                            <li>
                                <a href="{% url "cart:cart_detail" %}">
                                    <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
                                    <span class="badge">
                                        {% with total_items=cart|length %}
                                            {% if cart|length > 0 %}
                                                {{ total_items }}
                                            {% else %}
                                                0
                                            {% endif %}
                                        {% endwith %}
                                    </span>
                                    <p>{% trans 'cart' %}</p>
                                </a>
                            </li>
                        </ul>
                    </div> <!-- compare, wishlist, cart -->
                </div>
            </div>
        </div>
    </div>
</div>